server:
  port: 9800
spring:
  r2dbc:
    username: root
    password: Zyc19980518@
    url: r2dbc:mysql://${xiaos.datasource.host}:${xiaos.datasource.port}/${xiaos.datasource.database}?${xiaos.datasource.params}
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_empty

xiaos:
  cloud:
    register:
      namespace: cb64289f-e849-4fa5-ad04-a097defdd7d4
      group: dev
      username: nacos
      password: Zyc19980518@
      host: 124.223.92.239
      port: 8848
  datasource:
    database: user
    params: useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    host: localhost
    port: 3306